name: Egocentric Action
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: grep -q Luca README.md && echo "My name is in the readme, thanks!" || echo "My name is not in the readme... come on! I'll take care of it!"