name: Egocentric Action
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: COMMAND "check_state=$( grep -q "Luca" "README.md" )" >> "$GITHUB_ENV"
      - if: ${{ ! $check_state }}
        run: exit 1