name: Egocentric Action
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    env: 
      CHECK: ${{ grep -q Luca README.md }}
    steps:
      - run: $CHECK && echo "My name is in the readme, thanks!" || echo "My name is not in the readme..."